const userRoutes = {
    register: '/api/register',
    otpVerify: '/api/otpVerify',
    otpResend: '/api/otpResend',
    login: '/api/login',
    getUser: '/api/getUser',
    logout: '/api/logout',
    googAuth: '/api/googleAuth',
    checkMail: '/api/checkMail',
    verifyForgotPasswordOtp: '/api/verifyForgotPasswordOtp',
    resetPassword: '/api/resetPassword',
    updateProfile: '/api/updateProfile',
    updatePassword: '/api/updatePassword',
    updateIdentity: '/api/updateIdentity',
    updateBankAccount: '/api/updateBankAccount',
    addHotel: '/api/addHotel',
    getMyHotels: '/api/getMyHotels',
    getHotelData: '/api/getHotel',
    updateHotel: '/api/updateHotel',
    getAllHotels: '/api/getAllHotels',
    checkAvailability: '/api/checkAvailability',
    createPaymentIntent: '/api/createPaymentIntent',
    createBooking: '/api/createBooking',
    getBookedHotels: '/api/getBookedHotels',
    cancelBooking:'/api/cancelBooking',
    getSchedule: '/api/getSchedule',
    getToken:'/api/getToken',
    getMessage: '/api/getMessage',
    sendMessage: '/api/sendMessage',
    getMessagedUsers:'/api/getMessagedUsers',
    getReviews:'/api/getReviews',
    checkIfUserCanReview:'/api/checkIfUserCanReview',
    addReview:'/api/addReview',
}

export default userRoutes